### PR TITLE
A number of build changes, and one C++ style change.

### PR DESCRIPTION
**Pull request by nadiasvertex**
Some infrastructure changes. I plan on adding unit tests for the existing code. This will be easier than taking the existing alpha 1 codebase and writing tests for it.

### CODE REVIEW

**Comment by mtravis15432** [comment]
Couple things. Should I merge this into "mtravis" branch rather than master?

Also, I've had problems in the past with std::unordered_map, having to do with requiring special comparison functions to be written for a lot of things that boost's version didn't require. That's on gcc 4.7.2. That's basically the reason I didn't ditch boost.

Rest of the stuff looks good.

**Comment by nadiasvertex** [comment]
Yeah, mtravis.

boost's unordered_map is not as good as the standard's precisely because it
tries to make a generic hash function that is not really adequate. In
general, the standard one is very easy. All you have to do is provide a
specialization for std::hash...

template <>
  struct hash<Key>
  {
    std::size_t operator()(const Key& k) const
    {
     // hash in here.
    }

};

**Comment by mtravis15432** [comment]
OK, mind if I revert the map for now? Later on we can rip boost out along with putting in the right hash functions and whatever else std:: needs. Right now the thing isn't testable anyway.

**Comment by nadiasvertex** [comment]
You could... but I don't know why you would. It works right now. The code
_is_ testable right now. Each class needs to have tests written around the
basic operations to prove they actually work. For example, Field needs to
have tests around set and get to ensure that they do what you think and
return values of the appropriate size and type, respecting edge cases. It's
absolutely vital that an RDBMS is above reproach, and the best way to do
that is to have absolutely exhaustive unit tests for each piece of the
system. It also saves you massive amounts of time in a debugger because you
know where the bug is not. :-)

Your decision, though.

**Comment by nadiasvertex** [comment]
I might make one other point... unordered_map works by hashing the value.
If your hash function isn't good, the map won't perform well. Depending on
whatever "automatic" hashing function boost uses is probably a bad idea for
this very reason: it will tend to create an unbalanced, poorly performing
table. It is much better to stop and think about your data, choose or
create a hash function that uses the data correctly, and then write the
override.

**Comment by mtravis15432** [comment]
OK, I just pulled then pushed to branch mtravis. I rolled back the boost:: changes, and created a ticket https://github.com/infinisql/infinisql/issues/25 to yank out boost later that has hash functions for each key type. Looks great!

**Pull request closed without merging**
