### PR TITLE
install script should respect DESTDIR.

### PR DESCRIPTION
**Pull request by anatol**
DESTDIR is used during package stage installation.

Signed-off-by: Anatol Pomozov anatol.pomozov@gmail.com

### CODE REVIEW

**Comment by mtravis15432** [comment]
Pushed! Thank you.

**Comment by anatol** [comment]
Another change. Github tries to put it into the same pull request, but in fact this is a separate change.

**Comment by mtravis15432** [comment]
Hi, Anatol. I pushed your changes (plus one in gencfgenum.py that generates a python script) into the main repository. Didn't merge your pull request, instead just edited the files in my own repository and pushed.

**Comment by mtravis15432** [comment]
I edited these files manually and pushed.

**Pull request closed without merging**
